import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { store } from "@/lib/store";
import Link from "next/link";
import StoreProvider from "./StoreProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav>
          <Link href={"/home"} className="nav">
            Home
          </Link>
          <Link href={"/products"} className="nav">
            Products
          </Link>
          <Link href={"./.."} className="nav">
            Main
          </Link>
        </nav>
        <StoreProvider >
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
